[package]
name = "rusty_rogue"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tekenen = { path = "../tekenen/tekenen", features = ["image"] }
rand = "0.8.5"
once_cell = "1.18.0"